### ISSUE TITLE
It come to an error when running

### ISSUE THREAD

**Issue by fengqiangboy** [bitinn/kneesocks#7]
/usr/local/lib/node_modules/kneesocks/node_modules/socksv5/lib/client.js:225
  var args = normalizeConnectArgs(arguments),
             ^

TypeError: normalizeConnectArgs is not a function
    at Agent.exports.connect.exports.createConnection (/usr/local/lib/node_modules/kneesocks/node_modules/socksv5/lib/client.js:225:14)
    at Agent.createSocket (/usr/local/lib/node_modules/kneesocks/node_modules/socksv5/lib/Agents.js:225:21)
    at Agent.addRequest (/usr/local/lib/node_modules/kneesocks/node_modules/socksv5/lib/Agents.js:194:23)
    at new ClientRequest (_http_client.js:159:16)
    at Object.request (http.js:26:10)
    at Server.<anonymous> (/usr/local/lib/node_modules/kneesocks/lib/kneesocks.js:81:22)
    at emitTwo (events.js:106:13)
    at Server.emit (events.js:191:7)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:547:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)

**Comment by banana255** [comment]
I also have the same question in ubuntu 16.04. Do anyone know Why, 

thanks

**Comment by bitinn** [comment]
Related to Node 7, see this PR: https://github.com/mscdex/socksv5/pull/23

**Comment by banana255** [comment]
@bitinn thanks, after overwrite [socksv5/lib/client.js](https://github.com/mscdex/socksv5/pull/23/files#diff-50cfa59973c04321b5da0c6da0fdf4feR5) ,it works! 

**Thanks you very much!**
